[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "INET Showcases CN"
authors = [{name = "Graziella", email = "graziella@INET_Showcases_CN"}]
dynamic = ["version", "description"]
